---
abstract: 'create lightweight SCALARs with get/set callbacks'
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
  Test::Refcount: 0
configure_requires:
  Module::Build: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sentinel
provides:
  Sentinel:
    file: lib/Sentinel.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
